//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_Ukr
    {
        public string English { get; set; }
        public string Translation { get; set; }
        public int Correct { get; set; }
        public int Incorrect { get; set; }
        public string Type { get; set; }
    }
}
