//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eng_Ukr
    {
        public string English { get; set; }
        public int Correct { get; set; }
        public int Incorrect { get; set; }
        public string Type { get; set; }
        public string Translation { get; set; }
    }
}
